#:kivy 1.0.9
            
<WelcomePage>:
    survey: survey_button
    replay: replay_button
    mission: mission_button
    config: config_button

    GridLayout:
        cols: 2

        Button:
            id: survey_button
            text:"Survey"
        
        Button:
            id: replay_button
            text: "Replay"

        Button:
            id: mission_button
            text: "Mission"

        Button:
            id: config_button
            text: "Configurations"


   